package polymorphia.stepdefs;

import org.junit.jupiter.api.AfterEach;
import polymorphia.Polymorphia;
import polymorphia.artifacts.IArtifact;
import polymorphia.characters.Character;
import polymorphia.characters.CharacterFactory;
import polymorphia.maze.Maze;
import polymorphia.maze.RoomFactory;
import polymorphia.observers.EventBus;
import polymorphia.observers.TestObserver;

import java.util.HashMap;
import java.util.Map;

public class World {
    Polymorphia game;
    CharacterFactory characterFactory = new CharacterFactory();
    Map<String, Character> characters = new HashMap<>();
    Map<String, Double> initialHealth = new HashMap<>();
    Map<String, IArtifact> artifacts = new HashMap<>();
    private Maze maze;
    TestObserver observer;
    Maze.Builder mazeBuilder = Maze.getNewBuilder(new RoomFactory());

    public World() {
        observer = new TestObserver();
        EventBus.INSTANCE.attach(observer);
    }

    @AfterEach
    public void tearDown() {
        // clear old observers from singleton EventBus
        getGame().detach(observer);
        EventBus.INSTANCE.detachAll();
    }

    Polymorphia getGame() {
        if (game == null) {
            game = new Polymorphia(getMaze());
            game.attach(observer);
        }
        return game;
    }

    Maze getMaze() {
        if (maze == null) {
            try {
                maze = mazeBuilder.build();
            } catch (IllegalStateException e) {
                maze = mazeBuilder
                        .add(characterFactory.createKnight("AutoGeneratedKnight", 1.0))
                        .build();
            }
        }
        return maze;
    }

    public void createGame() {
        getGame();
    }

    public Character getCharacter(String characterName) {
        return characters.get(characterName);
    }

    public Double getInitialHealth(String characterName) {
        return initialHealth.get(characterName);
    }

    public IArtifact getArtifact(String name) {
        return artifacts.get(name);
    }

    public void putArtifact(String name, IArtifact artifact) {
        artifacts.put(name, artifact);
    }
}
