package com.cointrade.terminal.PostgreSQL;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

public class TradeTest {

    @Test
    void testConstructorSetsFieldsCorrectly() {
        User user = new User();
        user.setUsername("alice");

        Trade trade = new Trade("BTC", 1.5, 45000.0, user);

        assertEquals("BTC", trade.getSymbol());
        assertEquals(1.5, trade.getQuantity());
        assertEquals(45000.0, trade.getPrice());
        assertEquals(user, trade.getUser());
        assertNotNull(trade.getTimestamp());
    }

    @Test
    void testSettersAndGetters() {
        Trade trade = new Trade();
        User user = new User();
        user.setUsername("mark");

        LocalDateTime now = LocalDateTime.now();

        trade.setSymbol("ETH");
        trade.setQuantity(2.0);
        trade.setPrice(3200.0);
        trade.setTimestamp(now);
        trade.setUser(user);

        assertEquals("ETH", trade.getSymbol());
        assertEquals(2.0, trade.getQuantity());
        assertEquals(3200.0, trade.getPrice());
        assertEquals(now, trade.getTimestamp());
        assertEquals(user, trade.getUser());
    }

    @Test
    void testTimestampIsAutoGenerated() {
        User user = new User();
        Trade trade = new Trade("DOGE", 100.0, 0.08, user);

        assertNotNull(trade.getTimestamp());
        assertTrue(trade.getTimestamp().isBefore(LocalDateTime.now().plusSeconds(1)));
    }
}
